/* quiz.js - Minified */
'use strict';
let questions=[],currentQuestion=0,score=0,timeRemaining=0,totalQuizDuration=0,timerInterval,selectedAnswer=null,questionLimit=15,typingInterval,autoNextTimeout,shuffledQuestions=[],data=null,selectedLesson="সকল পাঠ",isPaused=false;
let startScreenHeading=null,startScreen=null,quizScreen=null,endScreen=null,questionElement=null,answerWrapperElement=null,nextButton=null,scoreElement=null,totalScoreElement=null,progressText=null,timer=null,previousButton=null,stopButton=null,pauseButton=null,errorMessage=null,startButton=null,quizHeading=null,numberProgressContainer=null,questionLimitInput=null,timeLimitInput=null,quizLessonDropdown=null,lessonDropdownMenu=null;
let subjectName;let questionHistory={};const dbName="quizHistoryDB";const storeName="questionHistoryStore";let db;

function openDatabase(){return new Promise((resolve,reject)=>{if(db){resolve(db);return;}const request=indexedDB.open(dbName,1);request.onerror=(e)=>{console.error("IndexedDB error:",e.target.error);reject("IndexedDB failed");};request.onsuccess=(e)=>{db=e.target.result;resolve(db);};request.onupgradeneeded=(e)=>{const db=e.target.result;if(!db.objectStoreNames.contains(storeName)){db.createObjectStore(storeName);}}});}
async function getQuestionHistoryFromDB(){await openDatabase();return new Promise((resolve,reject)=>{try{const t=db.transaction(storeName,"readonly");const s=t.objectStore(storeName);const r=s.get("questionHistory");r.onerror=(e)=>{reject(e.target.error);};r.onsuccess=(e)=>{resolve(e.target.result||{});};}catch(e){reject(e);}});}
async function saveQuestionHistoryToDB(h){await openDatabase();return new Promise((resolve,reject)=>{try{const t=db.transaction(storeName,"readwrite");const s=t.objectStore(storeName);const r=s.put(h,"questionHistory");r.onerror=(e)=>{reject(e.target.error);};r.onsuccess=()=>{resolve();};}catch(e){reject(e);}});}
function stripHTML(h){let t=document.createElement("div");t.innerHTML=h;return t.textContent||t.innerText||"";}
function containsImageMarker(t){if(typeof t!=="string"||!t)return false;return /(\(image\/[^\)]+\))|(<img.*?src=["']image\/[^"']+["'].*?>)/.test(t);}
async function saveQuestionHistory(){try{await saveQuestionHistoryToDB(questionHistory);}catch(e){console.error(e);}}
async function loadQuestionHistory(){try{const h=await getQuestionHistoryFromDB();questionHistory=(typeof h==='object'&&h!==null)?h:{};}catch(e){questionHistory={};displayError("Error loading history.");}}
async function loadQuestionData(){if(typeof questionsData==="undefined"){displayError("Data missing.");return null;}if(questionsData&&questionsData.sections){questionsData.sections.forEach(s=>{if(s&&s.section&&!questionHistory[s.section])questionHistory[s.section]={};});return questionsData;}displayError("Invalid data.");return null;}
function displayError(m){if(errorMessage){errorMessage.textContent=m;errorMessage.classList.remove("hide");errorMessage.style.opacity=1;}else{alert("Error: "+m);}}
function hideError(){if(errorMessage&&!errorMessage.classList.contains("hide")){errorMessage.textContent="";errorMessage.style.opacity=0;setTimeout(()=>{errorMessage.classList.add("hide");},300);}}
function restrictToNumbers(el){if(!el)return;el.addEventListener("input",function(){this.value=this.value.replace(/[^0-9]/g,"");});el.addEventListener("paste",function(e){let d=(e.clipboardData||window.clipboardData).getData("text");if(d.match(/[^0-9]/g))e.preventDefault();});}
loadQuestionHistory().then(()=>{loadQuestionData().then(d=>{if(d)data=d;});});

function validateInputs(){if(!questionLimitInput||!timeLimitInput||!startButton||!errorMessage)return;const q=parseInt(questionLimitInput.value),t=parseInt(timeLimitInput.value),max=parseInt(questionLimitInput.max),min=parseInt(questionLimitInput.min);let e="";if(isNaN(q)||isNaN(t))e="Invalid numbers.";else if(!isNaN(min)&&(q<min||t<min))e=`Min limit is ${min}.`;else if(!isNaN(max)&&(q>max||t>max))e=`Max limit is ${max}.`;const errShowing=!errorMessage.classList.contains("hide")&&errorMessage.textContent.includes("No questions");startButton.disabled=!!e||errShowing;if(e)displayError(e);else if(!errShowing)hideError();}
async function startQuiz(){if(!questionLimitInput||!timeLimitInput||!quizLessonDropdown||!startButton||!data||!subjectName){displayError("Init error.");return;}const qVal=parseInt(questionLimitInput.value),tVal=parseInt(timeLimitInput.value);validateInputs();if(startButton.disabled)return;questionLimit=qVal;totalQuizDuration=tVal*60;timeRemaining=totalQuizDuration;currentQuestion=0;score=0;selectedAnswer=null;isPaused=false;selectedLesson=quizLessonDropdown.value;const sec=data.sections.find(s=>s.section===subjectName);let base=(sec&&sec.questions)?sec.questions.filter(q=>q&&q.question):[];if(base.length===0){displayError("No questions.");return;}let filtered=filterQuestions(base,selectedLesson);if(filtered.length===0){displayError("No questions for filter.");return;}if(qVal>filtered.length){questionLimit=filtered.length;questionLimitInput.value=questionLimit;if(tVal>filtered.length){timeLimitInput.value=questionLimit;totalQuizDuration=questionLimit*60;timeRemaining=totalQuizDuration;}}else{questionLimit=Math.min(qVal,filtered.length);}try{shuffledQuestions=await selectQuestions(filtered,questionLimit,subjectName,selectedLesson);}catch(e){displayError("Error prep questions.");return;}if(!shuffledQuestions.length){displayError("No questions selected.");return;}shuffledQuestions.forEach(q=>{if(q){q.answered=false;q.selectedAnswer=null;q.isCorrect=null;}});hideError();startScreen.classList.add("hide");quizScreen.classList.remove("hide");showQuiz();if(quizHeading)typeText(quizHeading,subjectName,30);startTimer();displayQuestion();}

function getCurrentFilterText(){if(quizLessonDropdown&&quizLessonDropdown.selectedIndex>=0)return quizLessonDropdown.options[quizLessonDropdown.selectedIndex].text;return selectedLesson==="image_questions_only"?"শুধুমাত্র ছবিযুক্ত প্রশ্ন":"সকল পাঠ";}
function filterQuestions(qs,filter){if(!Array.isArray(qs))return[];if(filter==="image_questions_only"){return qs.filter(q=>{if(!q||!q.question)return false;if(containsImageMarker(q.question))return true;if(q.options&&Array.isArray(q.options))return q.options.some(o=>o&&containsImageMarker(Object.keys(o)[0]));return false;});}else if(filter!=="সকল পাঠ"){return qs.filter(q=>q&&q.lesson===filter);}return qs.filter(q=>q&&q.question);}
async function selectQuestions(avail,limit,sub,filter){let key=filter==="image_questions_only"?`${sub}-images_only`:(filter==="সকল পাঠ"?`${sub}-all`:`${sub}-${filter}`);const actLimit=Math.min(limit,avail.length);if(!questionHistory[sub])questionHistory[sub]={};if(!questionHistory[sub][key])questionHistory[sub][key]=[];let unseen=avail.filter(q=>q&&q.question&&!questionHistory[sub][key].includes(q.question));let seen=avail.filter(q=>q&&q.question&&questionHistory[sub][key].includes(q.question));if(unseen.length===0&&seen.length===avail.length&&avail.length>0){questionHistory[sub][key]=[];unseen=avail;seen=[];}let sel=[];unseen=shuffleArray(unseen);let take=Math.min(actLimit,unseen.length);sel=unseen.slice(0,take);sel.forEach(q=>{if(q&&!questionHistory[sub][key].includes(q.question))questionHistory[sub][key].push(q.question);});const rem=actLimit-sel.length;if(rem>0&&seen.length>0){seen=shuffleArray(seen);sel.push(...seen.slice(0,Math.min(rem,seen.length)));}let att=0;while(sel.length<actLimit&&att<avail.length*2){const r=avail[Math.floor(Math.random()*avail.length)];if(r&&!sel.some(sq=>sq.question===r.question))sel.push(r);att++;}await saveQuestionHistory();return shuffleArray(sel);}

function convertNewlinesToHtml(t){return typeof t==="string"?t.replace(/\n/g,"<br>"):"";}
function processTextWithImages(t){if(typeof t!=="string")return"";return t.replace(/(\(image\/([^\)]+)\))|(<img.*?src=["'](image\/[^"']+)["'].*?>)/g,(m,p1,ifn,p3,isrc)=>{let f=p1?"image/"+ifn:isrc;if(!f||f.trim()==="image/")return m;return `<div><img src="${f}" style="max-width:100%;height:auto;display:block;margin:5px auto;" alt="Image" ondragstart="return false;"></div>`;});}
function displayQuestion(){if(!questionElement||!shuffledQuestions[currentQuestion]){stopQuiz();return;}const qd=shuffledQuestions[currentQuestion];pauseButton.classList.add("hide");clearPreviousContent();let qc=processTextWithImages(qd.question);qc=qc.replace(/'([^']+)'/g,"<span class='highlight'>$1</span>");qc=qc.replace(/<[^>]*class="mathy"[^>]*>(.*?)<\/[^>]*>/g,(_m,p1)=>`<script type="math/asciimath">${p1.replace(/<[^>]*>/g,"")}</script>`);questionElement.innerHTML=`<h5>${convertNewlinesToHtml(qc)}</h5>`;if(typeof MathJax!=="undefined"&&MathJax.Hub)try{MathJax.Hub.Queue(["Typeset",MathJax.Hub,questionElement]);}catch(e){}displayAnswers(qd);answerWrapperElement.style.opacity="1";answerWrapperElement.style.animation="fadeInUp 0.5s ease-out";previousButton.disabled=currentQuestion===0;nextButton.disabled=(currentQuestion===shuffledQuestions.length-1)&&qd.answered;if(shuffledQuestions.length<=1){nextButton.disabled=true;previousButton.disabled=true;}updateQuestionCounter();addHighlightCSS();}
function addHighlightCSS(){if(document.getElementById("highlight-styles"))return;const s=document.createElement("style");s.id="highlight-styles";s.innerHTML=`.highlight{display:inline-block;background:linear-gradient(90deg,#84fab0,#8fd3f4);font-weight:bold;border-radius:8px;padding:3.5px 6px;margin:2.5px 4px;color:#fff;box-shadow:1px 1px 3px rgba(0,0,0,0.2)}.explanation-container{margin-top:25px;padding-top:15px;border-top:1px dashed #ccc;animation:fadeInUp 0.8s ease-out;text-align:left}.explanation-heading{font-size:1.1em;font-weight:bold;color:#0056b3;margin-bottom:12px;display:flex;align-items:center}.explanation-heading-text{margin-right:8px}.explanation-arrow-image{width:24px;height:auto;transform:rotate(350deg);margin-top:2px}.question-explanation{padding:15px;background-color:#f8f9fa;border:1px solid #dee2e6;border-radius:8px;color:#343a40;font-size:0.95em;line-height:1.6;box-shadow:inset 0 1px 3px rgba(0,0,0,0.05);word-wrap:break-word;overflow-y:auto;max-height:300px;text-align:left}.question-explanation img{max-width:100%;height:auto;display:block;margin:10px auto;border-radius:4px}.question-explanation .MathJax_Display{overflow-x:auto;overflow-y:hidden;max-width:100%}`;document.head.appendChild(s);}

function clearPreviousContent(){if(answerWrapperElement){answerWrapperElement.innerHTML="";answerWrapperElement.style.opacity="0";}if(questionElement)questionElement.innerHTML="";clearTimeout(autoNextTimeout);clearInterval(typingInterval);}
function updateQuestionCounter(){const c=document.querySelector(".current"),t=document.querySelector(".total");if(c)c.textContent=currentQuestion+1;if(t)t.textContent=shuffledQuestions.length;}
function addExplanationBlock(qd,tgt){if(!qd||!qd.explanation||!tgt||tgt.querySelector(".explanation-container"))return;const c=document.createElement("div");c.className="explanation-container";c.innerHTML=`<h4 class="explanation-heading"><span class="explanation-heading-text">Explanation</span><img src="12arrow.png" alt="->" class="explanation-arrow-image"></h4>`;const d=document.createElement("div");d.className="question-explanation";let ct=processTextWithImages(qd.explanation);ct=ct.replace(/<[^>]*class="mathy"[^>]*>(.*?)<\/[^>]*>/g,(_m,p1)=>`<script type="math/asciimath">${p1.replace(/<[^>]*>/g,"")}</script>`);d.innerHTML=convertNewlinesToHtml(ct);c.appendChild(d);tgt.appendChild(c);if(typeof MathJax!=="undefined"&&MathJax.Hub)try{MathJax.Hub.Queue(["Typeset",MathJax.Hub,d]);}catch(e){}}
function displayAnswers(qd){if(!answerWrapperElement||!qd.options)return;answerWrapperElement.innerHTML="";qd.options.forEach(o=>{if(typeof o!=="object")return;const txt=Object.keys(o)[0],corr=o[txt],btn=document.createElement("div");btn.classList.add("answer");if(corr)btn.classList.add("c");let ct=processTextWithImages(txt);ct=ct.replace(/<[^>]*class="mathy"[^>]*>(.*?)<\/[^>]*>/g,(_m,p1)=>`<script type="math/asciimath">${p1.replace(/<[^>]*>/g,"")}</script>`);btn.innerHTML=convertNewlinesToHtml(ct);if(qd.answered){btn.classList.add("disabled");if(corr)btn.classList.add("correct");else if(txt===qd.selectedAnswer)btn.classList.add("wrong");}else{btn.addEventListener("click",()=>selectAnswer(btn,o));}answerWrapperElement.appendChild(btn);});if(qd.answered)addExplanationBlock(qd,answerWrapperElement);if(typeof MathJax!=="undefined"&&MathJax.Hub)try{MathJax.Hub.Queue(["Typeset",MathJax.Hub,answerWrapperElement]);}catch(e){}}
function isCorrectAnswer(o){return typeof o==="object"&&Object.values(o)[0]===true;}
function selectAnswer(btn,opt){if(shuffledQuestions[currentQuestion].answered)return;clearTimeout(autoNextTimeout);const qd=shuffledQuestions[currentQuestion],corr=isCorrectAnswer(opt);qd.answered=true;qd.selectedAnswer=Object.keys(opt)[0];qd.isCorrect=corr;answerWrapperElement.querySelectorAll(".answer").forEach(a=>a.classList.add("disabled"));btn.classList.add("selected");if(corr){btn.classList.add("correct");score++;}else{btn.classList.add("wrong");const c=answerWrapperElement.querySelector(".answer.c");if(c)c.classList.add("correct");}const exp=qd.explanation&&qd.explanation.trim()!=="";if(exp){addExplanationBlock(qd,answerWrapperElement);pauseButton.classList.remove("hide");}else{pauseButton.classList.add("hide");}autoNextTimeout=setTimeout(()=>{if(!isPaused)nextQuestion();},exp?3000:500);nextButton.disabled=(currentQuestion===shuffledQuestions.length-1);}

function findNextUnansweredQuestion(){for(let i=currentQuestion+1;i<shuffledQuestions.length;i++)if(!shuffledQuestions[i].answered)return i;for(let i=0;i<currentQuestion;i++)if(!shuffledQuestions[i].answered)return i;return-1;}
function nextQuestion(){clearInterval(typingInterval);clearTimeout(autoNextTimeout);pauseButton.classList.add("hide");if(isPaused){isPaused=false;startTimer();}const n=findNextUnansweredQuestion();if(n!==-1){currentQuestion=n;selectedAnswer=null;displayQuestion();}else{endQuiz();}}
function previousQuestion(){clearInterval(typingInterval);clearTimeout(autoNextTimeout);pauseButton.classList.add("hide");if(isPaused){isPaused=false;startTimer();}if(currentQuestion>0){currentQuestion--;selectedAnswer=null;displayQuestion();nextButton.disabled=(currentQuestion===shuffledQuestions.length-1)&&shuffledQuestions[currentQuestion]?.answered;}}
function stopQuiz(){clearInterval(timerInterval);clearTimeout(autoNextTimeout);isPaused=false;quizScreen.classList.add("hide");endScreen.classList.remove("hide");pauseButton.classList.add("hide");hideQuiz();calculateAndDisplayResults();nextButton.disabled=false;}
function calculateAndDisplayResults(){if(!scoreElement){scoreElement=document.querySelector(".final-score");totalScoreElement=document.querySelector(".total-score");}let c=0,w=0;shuffledQuestions.forEach(q=>{if(q.answered){if(q.isCorrect)c++;else w++;}});const t=shuffledQuestions.length,na=t-(c+w),els=[{e:scoreElement,v:c},{e:totalScoreElement,v:t},{e:document.querySelector(".correct-count"),v:c},{e:document.querySelector(".wrong-count"),v:w},{e:document.querySelector(".not-answered-count"),v:na}];function typeNext(i){if(i>=els.length)return;const item=els[i];if(item.e)typeText(item.e,item.v.toString(),100,()=>typeNext(i+1));else typeNext(i+1);}typeNext(0);}
function endQuiz(){stopQuiz();}
function startTimer(){if(!progressText)return;const pb=document.querySelector(".progress-bar");clearInterval(timerInterval);if(totalQuizDuration<=0){if(pb)pb.style.width='0%';progressText.innerHTML="0s";return;}const up=()=>{if(timeRemaining<0)timeRemaining=0;const h=Math.floor(timeRemaining/3600),m=Math.floor((timeRemaining%3600)/60),s=timeRemaining%60,ts=h>0?`${h}h ${m.toString().padStart(2,'0')}m ${s.toString().padStart(2,'0')}s`:m>0?`${m}m ${s.toString().padStart(2,'0')}s`:`${s}s`;progressText.innerHTML=ts;const p=(timeRemaining/totalQuizDuration)*100;if(pb){pb.style.width=`${Math.max(0,p)}%`;pb.style.backgroundColor=p<20?'#dc3545':p<50?'#ffc107':'#28a745';progressText.style.color=p>=49.5?"#fff":"#000";}};up();timerInterval=setInterval(()=>{if(!isPaused){if(timeRemaining>0){timeRemaining--;up();}else{clearInterval(timerInterval);endQuiz();}}},1000);}

async function restartQuiz(){clearInterval(timerInterval);clearTimeout(autoNextTimeout);isPaused=false;endScreen.classList.add("hide");quizScreen.classList.add("hide");startScreen.classList.remove("hide");pauseButton.classList.add("hide");hideError();currentQuestion=0;score=0;selectedAnswer=null;shuffledQuestions=[];timeRemaining=0;try{await loadQuestionHistory();const d=await loadQuestionData();if(d&&subjectName){data=d;populateLessonDropdown(subjectName);showStartScreen(subjectName);}}catch(e){displayError("Error restarting.");}}
function handlePauseButtonClick(){if(pauseButton&&!pauseButton.classList.contains("hide")&&!isPaused){isPaused=true;clearInterval(timerInterval);clearTimeout(autoNextTimeout);pauseButton.classList.add("hide");}}
window.addEventListener("message",async(e)=>{const m=e.data;if(m&&m.subjectName){subjectName=m.subjectName;if(!startScreenHeading||!timeLimitInput)return;startScreenHeading.textContent="";timeLimitInput.value=15;questionLimitInput.value=15;quizLessonDropdown.value="সকল পাঠ";quizLessonDropdown.innerHTML="";lessonDropdownMenu.classList.add("hide");startButton.disabled=true;hideError();const l1=document.getElementById("time-limit-label"),l2=document.getElementById("question-limit-label"),l3=document.getElementById("quiz-lesson-label");if(l1)typeText(l1,"মিনিট নির্ধারণ করুন :",30);if(l2)typeText(l2,"প্রশ্নের সংখ্যা নির্ধারণ করুন :",30);if(startButton)typeText(startButton,"কুইজ শুরু করুন",30);if(l3)typeText(l3,"পাঠ নির্বাচন করুন :",30);try{await loadQuestionHistory();const d=await loadQuestionData();if(d){data=d;populateLessonDropdown(subjectName);showStartScreen(subjectName);}}catch(e){displayError("Load error.");}}else if(m==="closeQuiz")closeQuiz();else if(m==="reloadQuiz")restartQuiz();});
function closeQuiz(){clearInterval(timerInterval);clearTimeout(autoNextTimeout);isPaused=false;if(window.parent&&window.parent!==window)window.parent.postMessage("closeQuiz","*");if(quizScreen)quizScreen.classList.add('hide');}
function typeText(el,txt,spd,cb){return new Promise((res)=>{if(!el||typeof txt!=='string'){if(cb)cb();res();return;}if(el.typingInterval)clearInterval(el.typingInterval);let i=0;el.innerHTML="";el.typingInterval=setInterval(()=>{if(i>=txt.length){clearInterval(el.typingInterval);el.typingInterval=null;if(cb)cb();res();}else{el.textContent+=txt.charAt(i);i++;}},spd);});}
function shuffleArray(arr){if(!Array.isArray(arr))return arr;const s=[...arr];for(let i=s.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[s[i],s[j]]=[s[j],s[i]];}return s;}
function showQuiz(){if(quizScreen&&quizHeading){quizScreen.classList.add("show");quizScreen.classList.remove("hide");document.body.style.backgroundColor="#fff";quizHeading.textContent="";typeText(quizHeading,subjectName||"Quiz",30);}}
function hideQuiz(){if(quizScreen){quizScreen.classList.remove("show");quizScreen.classList.add("hide");document.body.style.backgroundColor="";}}
function populateLessonDropdown(sub){if(!quizLessonDropdown||!data||!data.sections)return;const sec=data.sections.find(s=>s.section===sub);let qs=(sec&&sec.questions)?sec.questions.filter(q=>q&&q.question):[];let hasImg=false,hasLes=false;const uLes=new Set();qs.forEach(q=>{if(!hasImg){if(containsImageMarker(q.question))hasImg=true;else if(q.options&&q.options.some(o=>typeof o==='object'&&containsImageMarker(Object.keys(o)[0])))hasImg=true;}if(q.lesson&&q.lesson.trim()){hasLes=true;uLes.add(q.lesson.trim());}});quizLessonDropdown.innerHTML="";if(qs.length===0||(!hasLes&&!hasImg)){if(lessonDropdownMenu)lessonDropdownMenu.classList.add("hide");quizLessonDropdown.disabled=true;selectedLesson="সকল পাঠ";return;}if(lessonDropdownMenu)lessonDropdownMenu.classList.remove("hide");quizLessonDropdown.disabled=false;const a=document.createElement("option");a.value="সকল পাঠ";a.textContent="সকল পাঠ";quizLessonDropdown.appendChild(a);if(hasImg){const i=document.createElement("option");i.value="image_questions_only";i.textContent="শুধুমাত্র ছবিযুক্ত প্রশ্ন";quizLessonDropdown.appendChild(i);}if(hasLes){Array.from(uLes).sort().forEach(l=>{const o=document.createElement("option");o.value=l;o.textContent=l;quizLessonDropdown.appendChild(o);});}quizLessonDropdown.value="সকল পাঠ";selectedLesson="সকল পাঠ";}
function updateMinLimitsForLesson(){if(!questionLimitInput||!timeLimitInput||!questions)return;const f=quizLessonDropdown.disabled?"সকল পাঠ":quizLessonDropdown.value,qs=filterQuestions(questions,f),max=qs.length;let min=max>0?(max<10?1:15):1;min=Math.min(min,max);if(min<1)min=1;if(max<=0){questionLimitInput.max=1;timeLimitInput.max=1;if(lessonDropdownMenu&&!lessonDropdownMenu.classList.contains("hide"))displayError("No questions.");}else{questionLimitInput.max=max;timeLimitInput.max=max;hideError();}questionLimitInput.min=min;timeLimitInput.min=min;const cQ=parseInt(questionLimitInput.value)||min,cT=parseInt(timeLimitInput.value)||min;questionLimitInput.value=Math.min(Math.max(cQ,min),Math.max(min,parseInt(questionLimitInput.max)));timeLimitInput.value=Math.min(Math.max(cT,min),Math.max(min,parseInt(timeLimitInput.max)));validateInputs();}
function showStartScreen(sub){if(!startScreen||!data)return;typeText(startScreenHeading,sub,30);const sec=data.sections.find(s=>s.section===sub);questions=(sec&&sec.questions)?sec.questions.filter(q=>q&&q.question):[];if(questions.length>0){questionLimitInput.disabled=false;timeLimitInput.disabled=false;updateMinLimitsForLesson();}else{questionLimitInput.disabled=true;timeLimitInput.disabled=true;quizLessonDropdown.disabled=true;if(lessonDropdownMenu)lessonDropdownMenu.classList.add("hide");startButton.disabled=true;displayError(`No questions for "${sub}".`);}startScreen.classList.remove("hide");quizScreen.classList.add("hide");endScreen.classList.add("hide");}
document.addEventListener("DOMContentLoaded",()=>{startScreenHeading=document.getElementById("start-screen-heading");startScreen=document.querySelector(".start-screen");quizScreen=document.querySelector(".quiz");endScreen=document.querySelector(".end-screen");questionElement=document.querySelector(".question");answerWrapperElement=document.querySelector(".answer-wrapper");nextButton=document.querySelector(".next");scoreElement=document.querySelector(".final-score");totalScoreElement=document.querySelector(".total-score");progressText=document.querySelector(".progress-text");timer=document.querySelector(".timer");previousButton=document.querySelector(".previous");stopButton=document.querySelector(".stop");pauseButton=document.querySelector(".pause");errorMessage=document.querySelector(".error-message");startButton=document.querySelector(".start");quizHeading=document.querySelector(".quiz-heading");numberProgressContainer=document.querySelector(".number-progress");questionLimitInput=document.getElementById("question-limit");timeLimitInput=document.getElementById("time-limit");quizLessonDropdown=document.getElementById("quiz-lesson");lessonDropdownMenu=document.getElementById("lesson-dropdown-menu");if(quizScreen)quizScreen.classList.add("hide");if(endScreen)endScreen.classList.add("hide");if(startScreen)startScreen.classList.add("hide");if(pauseButton)pauseButton.classList.add("hide");if(lessonDropdownMenu)lessonDropdownMenu.classList.add("hide");if(errorMessage)errorMessage.classList.add("hide");if(startButton)startButton.disabled=true;if(startButton)startButton.addEventListener("click",startQuiz);if(nextButton)nextButton.addEventListener("click",nextQuestion);if(previousButton)previousButton.addEventListener("click",previousQuestion);if(stopButton)stopButton.addEventListener("click",stopQuiz);if(pauseButton)pauseButton.addEventListener("click",handlePauseButtonClick);const rb=document.querySelector(".restart");if(rb)rb.addEventListener("click",restartQuiz);if(quizLessonDropdown)quizLessonDropdown.addEventListener("change",function(){selectedLesson=this.value;updateMinLimitsForLesson();});if(questionLimitInput){questionLimitInput.addEventListener("input",validateInputs);restrictToNumbers(questionLimitInput);}if(timeLimitInput){timeLimitInput.addEventListener("input",validateInputs);restrictToNumbers(timeLimitInput);}if(window.parent&&window.parent!==window)window.parent.postMessage("quizReady","*");});
async function clearQuestionHistory(){try{await saveQuestionHistoryToDB({});questionHistory={};console.log("History cleared.");}catch(e){console.error(e);}}
